import { readFile, readdir, stat } from 'node:fs/promises'
import { resolve, relative } from 'node:path'

export type ProjectMeta = {
  rootDir: string
  directoryTree?: string
  projectIntroContent?: string
  packageJsonContent?: string
  readmeContent?: string
}

const IGNORE_PATTERNS = [
  'node_modules',
  '.git',
  'dist',
  'state',
  '*.log',
]

function shouldIgnore(name: string): boolean {
  return IGNORE_PATTERNS.some((pattern) => {
    if (pattern.includes('*')) {
      return name.endsWith(pattern.slice(1))
    }
    return name === pattern
  })
}

async function buildDirectoryTree(dir: string, depth = 0): Promise<string> {
  const entries = await readdir(dir)
  const lines: string[] = []
  for (const entry of entries.sort()) {
    if (shouldIgnore(entry)) continue
    const fullPath = resolve(dir, entry)
    const s = await stat(fullPath)
    const prefix = '  '.repeat(depth)
    if (s.isDirectory()) {
      lines.push(`${prefix}├── ${entry}/`)
      lines.push(await buildDirectoryTree(fullPath, depth + 1))
    } else {
      lines.push(`${prefix}├── ${entry}`)
    }
  }
  return lines.join('\n')
}

function contentLikelyContainsDirectoryTree(content: string): boolean {
  return content.includes('├──') || content.includes('目录结构')
}

export async function loadProjectMeta(opts: {
  projectRoot: string
  projectIntroPath?: string
  autoGenerateDirectoryTree?: boolean
}): Promise<ProjectMeta> {
  const rootDir = resolve(process.cwd(), opts.projectRoot)
  let projectIntroContent: string | undefined
  let directoryTree: string | undefined

  if (opts.projectIntroPath) {
    try {
      projectIntroContent = await readFile(resolve(rootDir, opts.projectIntroPath), 'utf8')
    } catch {
      console.log('[提示] 配置的 projectIntroPath 不存在，请输入项目介绍文档的路径：')
    }
  }

  if (opts.autoGenerateDirectoryTree) {
    if (!projectIntroContent || !contentLikelyContainsDirectoryTree(projectIntroContent)) {
      directoryTree = await buildDirectoryTree(rootDir)
    }
  }

  let packageJsonContent: string | undefined
  let readmeContent: string | undefined

  try {
    packageJsonContent = await readFile(resolve(rootDir, 'package.json'), 'utf8')
  } catch {}
  try {
    const readmeCandidates = ['README.md', 'readme.md', 'README']
    for (const candidate of readmeCandidates) {
      try {
        readmeContent = await readFile(resolve(rootDir, candidate), 'utf8')
        break
      } catch {}
    }
  } catch {}

  return {
    rootDir,
    directoryTree,
    projectIntroContent,
    packageJsonContent,
    readmeContent,
  }
}
